//PACKAGE COM.FRIENDLYHAND.SERVICE;
//
//IMPORT JAVA.IO.FILENOTFOUNDEXCEPTION;
//IMPORT JAVA.IO.IOEXCEPTION;
//IMPORT JAVA.UTIL.LIST;
//
//IMPORT ORG.SPRINGFRAMEWORK.BEANS.FACTORY.ANNOTATION.AUTOWIRED;
//IMPORT ORG.SPRINGFRAMEWORK.STEREOTYPE.SERVICE;
//
//IMPORT COM.FRIENDLYHAND.MODEL.CLIENTE;
//IMPORT COM.FRIENDLYHAND.MODEL.DADOS;
//IMPORT COM.FRIENDLYHAND.MODEL.MENSAGEMRETORNO;
//IMPORT COM.FRIENDLYHAND.REPOSITORY.REPOSITORY;
//
//@SERVICE
//PUBLIC CLASS CLIENTESERVICE {
//	
//	@AUTOWIRED
//	REPOSITORY REPO;
//	
//	/*------------MOSTRAR UM CLIENTE-----------*/
//	PUBLIC CLIENTE GETCLIENTE(INT ID) THROWS FILENOTFOUNDEXCEPTION, CLASSNOTFOUNDEXCEPTION, IOEXCEPTION {
//
//		DADOS DADOS = REPO.LERARQUIVO();
//		
//		FOR (INT I = 0; I < DADOS.GETCLIENTES().SIZE(); I++) {
//			
//			IF(DADOS.GETCLIENTES().GET(I).GETID()==ID) {
//				RETURN DADOS.GETCLIENTES().GET(I);
//			}
//		}	
//		RETURN NULL;
//	}
//	
//	/*------------MOSTRAR TODOS OS CLIENTE-----------*/
//	PUBLIC LIST<CLIENTE> GETALLCLIENTES() THROWS FILENOTFOUNDEXCEPTION, CLASSNOTFOUNDEXCEPTION, IOEXCEPTION{
//		
//		DADOS DADOS = REPO.LERARQUIVO();
//		RETURN DADOS.GETCLIENTES();
//
//	}
//	
//	/*------------CRIAR UM CLIENTE-----------*/
//	PUBLIC CLIENTE CREATECLIENTE(CLIENTE CLIENTE) THROWS FILENOTFOUNDEXCEPTION, CLASSNOTFOUNDEXCEPTION, IOEXCEPTION {
//		
//		DADOS DADOS = REPO.LERARQUIVO();
//		IF(DADOS.GETCLIENTES().SIZE()==0) {
//			CLIENTE.SETID(1);
//			DADOS.GETCLIENTES().ADD(CLIENTE);
//		}ELSE {
//			INT ULTIMOID = DADOS.GETCLIENTES().GET(DADOS.GETCLIENTES().SIZE()-1).GETID();
//			CLIENTE.SETID(ULTIMOID+1);
//			DADOS.GETCLIENTES().ADD(CLIENTE);
//		}
//		REPO.GRAVARARQUIVO(DADOS);
//		RETURN CLIENTE;
//	}
//
//
//	/*------------ATUALIZAR UM CLIENTE-----------*/
//	PUBLIC CLIENTE UPDATECLIENTE(CLIENTE CLIENTE, INT ID) THROWS FILENOTFOUNDEXCEPTION, CLASSNOTFOUNDEXCEPTION, IOEXCEPTION {
//		
//		DADOS DADOS = REPO.LERARQUIVO();
//		FOR (INT I = 0; I < DADOS.GETCLIENTES().SIZE(); I++) {
//			IF(DADOS.GETCLIENTES().GET(I).GETID()==ID) {
//				
//				DADOS.GETCLIENTES().GET(I).SETNOME(CLIENTE.GETNOME());
//				DADOS.GETCLIENTES().GET(I).SETEMAIL(CLIENTE.GETEMAIL());
//				DADOS.GETCLIENTES().GET(I).SETCPF(CLIENTE.GETCPF());
//				DADOS.GETCLIENTES().GET(I).SETDATANASCIMENTO(CLIENTE.GETDATANASCIMENTO());
//				DADOS.GETCLIENTES().GET(I).SETSENHA(CLIENTE.GETSENHA());
//				DADOS.GETCLIENTES().GET(I).SETENDERECO(CLIENTE.GETENDERECO());
//				
//				REPO.GRAVARARQUIVO(DADOS);
//				
//				RETURN DADOS.GETCLIENTES().GET(I);
//			}
//		}
//
//		RETURN NULL;
//	}
//	
//	/*------------DELETAR UM CLIENTE-----------*/
//	PUBLIC MENSAGEMRETORNO DELETECLIENTE(INT ID) THROWS FILENOTFOUNDEXCEPTION, CLASSNOTFOUNDEXCEPTION, IOEXCEPTION {
//		
//		MENSAGEMRETORNO RETORNO = NEW MENSAGEMRETORNO();
//		
//		DADOS DADOS = REPO.LERARQUIVO();
//		FOR (INT I = 0; I < DADOS.GETCLIENTES().SIZE(); I++) {
//			IF(DADOS.GETCLIENTES().GET(I)!=NULL) {
//				IF(DADOS.GETCLIENTES().GET(I).GETID()==ID) {
//					DADOS.GETCLIENTES().SET(I, NULL);
//					REPO.GRAVARARQUIVO(DADOS);
//					RETORNO.SETSTATUS("OK");
//					RETORNO.SETMENSAGEM("CLIENTE DELETADO COM SUCESSO");
//					RETURN RETORNO;
//				}
//			}
//		}
//		
//		RETORNO.SETSTATUS("ERRO");
//		RETORNO.SETMENSAGEM("CLIENTE NÃO ENCONTRADO");
//		
//		RETURN RETORNO;
//	}
//	
//}
